services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=eu
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=123